
@host=http://localhost:5260

POST {{host}}/auth/Register
Content-Type: application/json

{

  "firstname":"mikeal",
  "lastname":"Abebe",
  "email":"mikealeabebebe@gmail.com",
  "password":"mikeal123"
}
