
@host=http://localhost:5260

POST {{host}}/auth/login
Content-Type: application/json

{
  "firstName":"Brook",
  "lastName":"Teferi",
  "email":"brookteferi1q2w@gmail.com",
  "password":"Brook123"
}
